ckpt = '../../output/ckpt/'
base_dir = '../../output/base/'
target_dir = '../../output/target/'
migrate_dir = '../../output/migrate/'
freezed_dir = '../../output/freezed/'
dyn_emb_dir = '../../output/dyn_emb/'
dyn_emb_out_dir = '../../output/dyn_emb_out/'